'use client';

import { useLanguage, LanguageProvider } from "@/context/LanguageContext";
import Navbar from "@/components/Navbar";
import Link from 'next/link';
import { useEffect, useState } from "react";

function PrivacyContent() {
    const { language, t } = useLanguage();
    const [sections, setSections] = useState<{ h: string, p: string }[]>([]);

    useEffect(() => {
        // Content data similar to script.js but imported here or defined here. 
        // For strict parity, I should probably move the content object to context or a separate file, 
        // but defining it here locally is fine if it's specific to this page.
        // HOWEVER, the legacy implementation had this content in privacy.html SCRIPT tag.

        const content = {
            en: [
                { h: "1. Overview", p: "CalmFlight (\"the App\") is designed to prioritize your privacy. We believe that your anxiety and personal health data are yours alone." },
                { h: "2. Data Collection", p: "We do not collect, transmit, or store any personal information. You do not need an account. We do not track your location, usage patterns, or device identifiers." },
                { h: "3. Data Storage", p: "All data generated by the App (such as your settings) is stored locally on your device. It is never uploaded to our servers." },
                { h: "4. Third-Party Access", p: "Since we do not collect data, we have no data to share with third parties. We do not sell or trade your information." },
                { h: "5. Support", p: "If you contact us via email, we use your address solely to respond to your inquiry. We do not share it with marketing lists." },
                { h: "6. Contact", p: "Questions? Contact us at <strong>contact@calmflightapp.com</strong>" }
            ],
            es: [
                { h: "1. Descripción General", p: "CalmFlight está diseñado para priorizar su privacidad. Creemos que sus datos de salud personal le pertenecen solo a usted." },
                { h: "2. Recopilación de Datos", p: "No recopilamos, transmitimos ni almacenamos ninguna información personal. No necesita una cuenta. No rastreamos su ubicación ni uso." },
                { h: "3. Almacenamiento", p: "Todos los datos generados por la App se almacenan localmente en su dispositivo. Nunca se suben a nuestros servidores." },
                { h: "4. Terceros", p: "Como no recopilamos datos, no tenemos nada que compartir con terceros. No vendemos su información." },
                { h: "5. Soporte", p: "Si nos contacta por correo, usamos su dirección solo para responderle. No la compartimos con listas de marketing." },
                { h: "6. Contacto", p: "¿Preguntas? Contáctenos en <strong>contact@calmflightapp.com</strong>" }
            ],
            fr: [
                { h: "1. Aperçu", p: "CalmFlight est conçu pour prioriser votre vie privée. Vos données de santé vous appartiennent." },
                { h: "2. Collecte de Données", p: "Nous ne collectons, ne transmettons et ne stockons aucune information personnelle. Aucun compte nécessaire. Pas de suivi." },
                { h: "3. Stockage", p: "Toutes les données sont stockées localement sur votre appareil. Elles ne sont jamais téléchargées sur nos serveurs." },
                { h: "4. Tiers", p: "Puisque nous ne collectons aucune donnée, nous n'en partageons aucune avec des tiers." },
                { h: "5. Support", p: "Si vous nous contactez par email, nous utilisons votre adresse uniquement pour répondre." },
                { h: "6. Contact", p: "Des questions ? Écrivez à <strong>contact@calmflightapp.com</strong>" }
            ],
            de: [
                { h: "1. Überblick", p: "CalmFlight priorisiert Ihre Privatsphäre. Ihre Gesundheitsdaten gehören allein Ihnen." },
                { h: "2. Datenerfassung", p: "Wir sammeln, übertragen oder speichern keine personenbezogenen Daten. Kein Konto erforderlich. Kein Tracking." },
                { h: "3. Speicherung", p: "Alle Daten werden lokal auf Ihrem Gerät gespeichert. Sie werden niemals auf unsere Server hochgeladen." },
                { h: "4. Dritte", p: "Da wir keine Daten sammeln, geben wir keine Daten an Dritte weiter." },
                { h: "5. Support", p: "Wenn Sie uns per E-Mail kontaktieren, verwenden wir Ihre Adresse nur zur Beantwortung." },
                { h: "6. Kontakt", p: "Fragen? Kontaktieren Sie uns unter <strong>contact@calmflightapp.com</strong>" }
            ]
        };

        // @ts-ignore
        setSections(content[language] || content['en']);
    }, [language]);

    return (
        <>
            <Navbar />
            <main className="pt-32 px-6 max-w-3xl mx-auto pb-20">
                <div className="ios-glass p-8 md:p-12">
                    <h1 className="text-3xl font-bold mb-2">{t('title_privacy')}</h1>
                    <p className="text-sm text-slate-400 mb-8">{t('date_privacy')}</p>

                    <div className="space-y-8 text-sm leading-relaxed text-slate-300">
                        {sections.map((sec, i) => (
                            <div key={i}>
                                <h3 className="text-white font-bold mb-2">{sec.h}</h3>
                                <p dangerouslySetInnerHTML={{ __html: sec.p }}></p>
                            </div>
                        ))}
                    </div>

                    <div className="mt-12 pt-8 border-t border-white/10 text-center">
                        <Link href="/" className="inline-flex items-center gap-2 text-blue-400 hover:text-blue-300 font-semibold text-sm">
                            <i className="ph-bold ph-arrow-left"></i>
                            <span>{t('back_home')}</span>
                        </Link>
                    </div>
                </div>
            </main>
        </>
    );
}

export default function PrivacyPage() {
    return (
        <LanguageProvider>
            <PrivacyContent />
        </LanguageProvider>
    );
}
